import { Boxes, Combine, LogOut, LucideHome, PackageSearch,
    BookMarked,Waypoints,BriefcaseBusiness,Database, Users, CalendarCheck2, 
    GraduationCap, Clipboard, ChevronRight, Component, ShieldPlus, TentTree, 
    Earth, Tent, Map, CircleSlash, BookOpenText, UserCheck, Smartphone, 
    MapPinned, LandPlot, FileCheck2Icon, UsersIcon, Globe, Briefcase, NotebookPen, 
    TrendingUp, User, ReceiptText, BookText, Calendar, 
    CreditCard,
    Sigma,
    Cpu,
    Settings,
    Menu,
    User2,
    Torus,
    UserIcon,
    Logs,
    GitPullRequest,
    UserPen,
    Upload,
    MapPin,
    ReceiptJapaneseYen, } from "lucide-react";
    export const Profile = [
        
        {
            'id':1,
            "menuName":'Profile Settings',
            "icon": <UserPen  className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'settings',
            "target":"_self",
            "access_by":[10],
            "userType":['E']
        },
        {
            'id':2,
            "menuName":'Document Upload',
            "icon":<Upload className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'upload-documents',
            "target":"_self",
            "access_by":[10],
            "userType":['E']
        },
    ]
    export const NavMenus = [
        {
            'id':1,
            "menu":'Home',
            "icon":<LucideHome className="text-card-foreground" size={15}/>,
            "submenu":[],
            "router-link":'/outlet/dashboard',
            "target":"_self",
            "access_by":[10],
            "userType":['E']
        },
        {
            'id':1,
            "menu":'Home',
            "icon":<LucideHome className="text-muted-foreground" size={15}/>,
            "submenu":[],
            "router-link":'/outlet/admin-dashboard',
            "target":"_self",
            "access_by":[1,9,2,12],
            "userType":["A"]
        },
        {
            'id':2,
            "menu":'Master',
            "icon":<Database  className="text-card-foreground" size={15}/>,
            "access_by":[1,9],
            "userType":["A"],
            "submenu":[
                {
                    'id':12,
                    "menu":'Common',
                    "icon":<Component  className="text-card-foreground" size={15}/>,
                    "submenu":[
                        {
                            'id':1,
                            "menu":'Category',
                            "icon":<PackageSearch className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/category',
                            "target":"_self",
                            "access_by":[1,9],
                        },   
                        {
                            'id':2,
                            "menu":'Units',
                            "icon":<Combine  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/units',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':3,
                            "menu":'Department',
                            "icon":<Boxes className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/department',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':5,
                            "menu":'Designation',
                            "icon":<BriefcaseBusiness  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/designation',
                            "target":"_self",
                            "access_by":[1,9],
                        
                        },
                        // {
                        //     'id':7,
                        //     "menu":'Earning Deduction',
                        //     "icon":<BookMarked  className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'master/earning-deduction',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        {
                            'id':9,
                            "menu":'Session',
                            "icon":<ShieldPlus   className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/session',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                         {
                            'id':32,
                            "menu":'Shift',
                            "icon":<User className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/shift',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':10,
                            "menu":'Holidays',
                            "icon":<TentTree   className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/holidays',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':11,
                            "menu":'Leave',
                            "icon":<TentTree   className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/leave',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        // {
                        //     'id':12,
                        //     "menu":'Salary Formula',
                        //     "icon":<Sigma className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'master/salaryFormula',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        {
                            'id':13,
                            "menu":'Country',
                            "icon":<Earth className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/country',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':14,
                            "menu":'Campus',
                            "icon":<Tent className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/campus',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':15,
                            "menu":'City',
                            "icon":<Map className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/city',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':16,
                            "menu":'Division',
                            "icon":<CircleSlash className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/division',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':17,
                            "menu":'Education Mode',
                            "icon":<BookOpenText className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/education-mode',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':18,
                            "menu":'Fellowship Status',
                            "icon":<UserCheck className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/fellowship-status',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':19,
                            "menu":'Job Nature',
                            "icon":<BriefcaseBusiness className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/job-nature',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':20,
                            "menu":'Mobile Code',
                            "icon":<Smartphone className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/mobile-code',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':21,
                            "menu":'Position',
                            "icon":<Component className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/position',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':22,
                            "menu":'State',
                            "icon":<MapPinned  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/state',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':23,
                            "menu":'Area',
                            "icon":<LandPlot className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/area',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':24,
                            "menu":'Academic Domain',
                            "icon":<GraduationCap className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/academic-domain',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':25,
                            "menu":'Academic Status',
                            "icon":<FileCheck2Icon className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/academic-status',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':26,
                            "menu":'Marital Status',
                            "icon":<UsersIcon className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/marital-status',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':27,
                            "menu":'Patent Status',
                            "icon":<UserCheck className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/patent-status',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':28,
                            "menu":'Region',
                            "icon":<Globe className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/region',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':29,
                            "menu":'Responsibility',
                            "icon":<Briefcase className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/responsibility',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':30,
                            "menu":'Written',
                            "icon":<NotebookPen className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/written',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':31,
                            "menu":'Employee Document Type',
                            "icon":<User className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'master/employee-doctype',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                    ],
                    "rightIcon":<ChevronRight className="text-card-foreground" size={15}/>,
                    "access_by":[1,9],
                },
                {
                    'id':13,
                    "menu":'Career',
                    "icon":<GraduationCap className="text-card-foreground" size={15}/>,
                    "submenu":[
                        // {
                        //     'id':1,
                        //     "menu":'Country',
                        //     "icon":<Earth className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/country',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':2,
                        //     "menu":'Campus',
                        //     "icon":<Tent className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/campus',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':3,
                        //     "menu":'City',
                        //     "icon":<Map className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/city',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':4,
                        //     "menu":'Division',
                        //     "icon":<CircleSlash className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/division',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':5,
                        //     "menu":'Education Mode',
                        //     "icon":<BookOpenText className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/education-mode',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':6,
                        //     "menu":'Fellowship Status',
                        //     "icon":<UserCheck className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/fellowship-status',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':7,
                        //     "menu":'Job Nature',
                        //     "icon":<BriefcaseBusiness className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/job-nature',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':8,
                        //     "menu":'Mobile Code',
                        //     "icon":<Smartphone className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/mobile-code',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':9,
                        //     "menu":'Position',
                        //     "icon":<Component className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/position',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':10,
                        //     "menu":'State',
                        //     "icon":<MapPinned  className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/state',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':11,
                        //     "menu":'Area',
                        //     "icon":<LandPlot className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/area',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':12,
                        //     "menu":'Academic Domain',
                        //     "icon":<GraduationCap className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/academic-domain',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':13,
                        //     "menu":'Academic Status',
                        //     "icon":<FileCheck2Icon className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/academic-status',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':14,
                        //     "menu":'Marital Status',
                        //     "icon":<UsersIcon className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/marital-status',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':15,
                        //     "menu":'Patent Status',
                        //     "icon":<UserCheck className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/patent-status',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':16,
                        //     "menu":'Region',
                        //     "icon":<Globe className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/region',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':17,
                        //     "menu":'Responsibility',
                        //     "icon":<Briefcase className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/responsibility',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        // {
                        //     'id':18,
                        //     "menu":'Written',
                        //     "icon":<NotebookPen className="text-card-foreground" size={15}/>,
                        //     "submenu":[],
                        //     "router-link":'/outlet/master/carrer/written',
                        //     "target":"_self",
                        //     "access_by":[1,9],
                        // },
                        {
                            'id':1,
                            "menu":'Career Apply',
                            "icon":<GraduationCap className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/carrer/carrerApply',
                            "target":"_self",
                            "access_by":[1,9]
                        },
                        {
                            'id':2,
                            "menu":'Career Step',
                            "icon":<TrendingUp className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/carrer/carrerStep',
                            "target":"_self",
                            "access_by":[1,9]
                        },
                        {
                            'id':3,
                            "menu":'Unit wise carrer applying mapping',
                            "icon":<GraduationCap   className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/carrer/unit-wise-carrere-applying-map',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':4,
                            "menu":'Unit wise career step mapping',
                            "icon":<Waypoints className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/carrer/unit-wise-career-step-map',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                    ],
                    "rightIcon":<ChevronRight className="text-card-foreground" size={15}/>,
                    "access_by":[1,9],
                },
                // {
                //     'id':14,
                //     "menu":'Mapping',
                //     "icon":<Waypoints  className="text-card-foreground" size={15}/>,
                //     "submenu":[
                //         {
                //             'id':11,
                //             "menu":'User wise unit mapping',
                //             "icon":<Waypoints className="text-card-foreground" size={15}/>,
                //             "submenu":[],
                //             "router-link":'/outlet/master/user-wise-unit-mapping',
                //             "target":"_self",
                //             "access_by":[1,9],
                //         },
                //         {
                //             'id':4,
                //             "menu":'Unit wise department mapping',
                //             "icon":<Waypoints    className="text-card-foreground" size={15}/>,
                //             "submenu":[],
                //             "router-link":'/outlet/master/unit-wise-department-mapping',
                //             "target":"_self",
                //             "access_by":[1,9],
                //         },
                //         {
                //             'id':6,
                //             "menu":'Unit wise designation mapping',
                //             "icon":<Waypoints  className="text-card-foreground" size={15}/>,
                //             "submenu":[],
                //             "router-link":'/outlet/master/unit-wise-designation-mapping',
                //             "target":"_self",
                //             "access_by":[1,9],
                //         },
                //         {
                //             'id':8,
                //             "menu":'Unit wise earning deduction mapping',
                //             "icon":<Waypoints   className="text-card-foreground" size={15}/>,
                //             "submenu":[],
                //             "router-link":'/outlet/master/unit-wise-earning-deduction-mapping',
                //             "target":"_self",
                //             "access_by":[1,9],
                //         },
                //         {
                //             'id':9,
                //             "menu":'Unit wise carrer applying mapping',
                //             "icon":<GraduationCap   className="text-card-foreground" size={15}/>,
                //             "submenu":[],
                //             "router-link":'/outlet/master/unit-wise-carrere-applying-map',
                //             "target":"_self",
                //             "access_by":[1,9],
                //         },
                //         {
                //             'id':12,
                //             "menu":'Unit wise career step mapping',
                //             "icon":<Waypoints className="text-card-foreground" size={15}/>,
                //             "submenu":[],
                //             "router-link":'/outlet/master/unit-wise-career-step-map',
                //             "target":"_self",
                //             "access_by":[1,9],
                //         },
                //     ],
                //     "rightIcon":<ChevronRight className="text-card-foreground" size={15}/>,
                //     "access_by":[1,9],

                // },
                {
                    'id':14,
                    "menu":'Common Mapping',
                    "icon":<Waypoints  className="text-card-foreground" size={15}/>,
                    "submenu":[
                        {
                            'id':11,
                            "menu":'User wise unit mapping',
                            "icon":<Waypoints className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/user-wise-unit-mapping',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':4,
                            "menu":'Unit wise department mapping',
                            "icon":<Waypoints    className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/unit-wise-department-mapping',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':6,
                            "menu":'Unit wise designation mapping',
                            "icon":<Waypoints  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/unit-wise-designation-mapping',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':7,
                            "menu":'Unit wise Employee Document Type mapping',
                            "icon":<Waypoints  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/unit-wise-emp-doc-type-map',
                            "target":"_self",
                            "access_by":[1,9],
                        }
                    ],
                    "rightIcon":<ChevronRight className="text-card-foreground" size={15}/>,
                    "access_by":[1,9],

                },
                {
                    'id':15,
                    "menu":'Salary',
                    "icon":<Waypoints  className="text-card-foreground" size={15}/>,
                    "submenu":[
                        {
                            'id':1,
                            "menu":'Earning Deduction',
                            "icon":<BookMarked  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/earning-deduction',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':2,
                            "menu":'Salary Formula',
                            "icon":<Sigma className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/salaryFormula',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':3,
                            "menu":'Unit wise earning deduction mapping',
                            "icon":<Waypoints   className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/unit-wise-earning-deduction-mapping',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':3,
                            "menu":'Unit wise user salary approve mapping',
                            "icon":<Waypoints   className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/unit-wise-salary-approve-map',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                    ],
                    "rightIcon":<ChevronRight className="text-card-foreground" size={15}/>,
                    "access_by":[1,9],

                },
                {
                    'id':16,
                    "menu":'Configure',
                    "icon":<Settings  className="text-card-foreground" size={15}/>,
                    "submenu":[
                        {
                            'id':1,
                            "menu":'Role',
                            "icon":<BookMarked  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/configure/role',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':2,
                            "menu":'Module',
                            "icon":<BookMarked  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/configure/module',
                            "target":"_self",
                            "access_by":[1,9],
                        },
                        {
                            'id':3,
                            "menu":'Role Wise Menu Access',
                            "icon":<BookMarked  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/configure/roleWiseMenuAccess',
                            "target":"_self",
                            "access_by":[1,9]
                        },
                        {
                            'id':4,
                            "menu":'APK Version',
                            "icon":<BookMarked  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/configure/apkVersion',
                            "target":"_self",
                            "access_by":[1,9]
                        },
                        {
                            'id':5,
                            "menu":'Menus',
                            "icon":<Menu  className="text-card-foreground" size={15}/>,
                            "submenu":[],
                            "router-link":'/outlet/master/configure/menu',
                            "target":"_self",
                            "access_by":[1,9]
                        },
                    ],
                    "rightIcon":<ChevronRight className="text-card-foreground" size={15}/>,
                    "access_by":[1,9],

                },
            ],
        },
        {
            'id':3,
            "menu":'Transaction',
            "icon":<Database  className="text-card-foreground" size={15}/>,
            "access_by":[1,8,9,12],
            "userType":["A"],
            "submenu":[
                {
                    'id':1,
                    "menu":'Employee',
                    "icon":<Users className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/transaction/employee',
                    "access_by":[1,8,9],
                },
                {
                    'id':2,
                    "menu":'Employee Attendance' ,
                    "icon":<CalendarCheck2 className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    // "router-link":'/outlet/transaction/employee/employeeAttendace',
                    "router-link":'/outlet/employeeAttendace',
                    "access_by":[1,8,9],
                },
                {
                    'id':3,
                    "menu":'Salary Process' ,
                    "icon":<Cpu className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/transaction/salary_process',
                    "access_by":[1,8,9],
                    
                },
                 {
                    'id':4,
                    "menu":'Employee Shift Schedule' ,
                    "icon":<CalendarCheck2 className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/shift-dtls',
                    "access_by":[],
                },
                {
                    'id':5,
                    "menu":'Salary Advance' ,
                    "icon":<CalendarCheck2 className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/transaction/salary-advance',
                    "access_by":[],
                }
            ],
            "router-link":'/outlet/transaction'
        },
        {
            'id':4,
            "menu":'Attendance',
            "icon":<CalendarCheck2  className="text-card-foreground" size={15}/>,
            "access_by":[1,8,2,9,12],
            "userType":["A"],
            "submenu":[
            
                {
                    'id':1,
                    "menu":'Attendance Report',
                    "icon":<Clipboard className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'attandance-report',
                    "target":"_self",
                    "access_by":[],
                },
                {
                    'id':2,
                    "menu":'Employee On-Duty/Off-Duty' ,
                    "icon":<CalendarCheck2 className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/employeeoffonDuty',
                    "access_by":[],
                },
                 {
                    'id':3,
                    "menu":'Manual Attandance' ,
                    "icon":<CalendarCheck2 className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/manual_attandance',
                    "access_by":[],
                }
               
            ],
        }, 
        {
            'id':6,
            "menu":'Profile',
            "icon":<User  className="text-card-foreground" size={15}/>,
            "access_by":[10],
            "userType":["E"],
            "submenu":[],
            "router-link":'/outlet/myProfile',
            "target":"_self"
        },
        {
            'id':5,
            "menu":'Me',
            "icon":<UserIcon  className="text-card-foreground" size={15}/>,
            "access_by":[10],
            "userType":["E"],
            "submenu":[
                {
                    'id':1,
                    "menu":'Attandance',
                    "icon":<Calendar className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/me/attendance',
                    "target":"_self",
                    "access_by":[],
                },
                {
                    'id':2,
                    "menu":'Leave' ,
                    "icon":<Torus className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/me/leave',
                    "access_by":[],
                }
            ],
        },
        // {
        //     'id':9,
        //     "menu":'Report',
        //     "icon":<ReceiptText  className="text-card-foreground" size={15}/>,
        //     "access_by":[1,8,9,10,12],
        //     "userType":["A","E"],
        //     "submenu":[] ,
        //     "router-link":'/outlet/payslip',
        //     "target":"_self"
        // },
       {
            'id':9,
            "menu":'Report',
            "icon":<UserIcon  className="text-card-foreground" size={15}/>,
            "access_by":[1,8,9,10,12],
            "userType":["A","E"],
            "submenu":[
                {
                    'id':1,
                    "menu":'Salary procees report',
                    "icon":<Calendar className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/payslip',
                    "target":"_self",
                    "access_by":[],
                },
                {
                    'id':2,
                    "menu":'Employee Shift Schedule Report',
                    "icon":<Torus className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/view-shift',
                    "access_by":[],
                },
                {
                    'id':3,
                    "menu":'Employee Shift Schedule Wise Attandance Compare',
                    "icon":<Torus className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/employeeShiftScheduleWiseAttendanceCompare',
                    "access_by":[],
                    
                },
                {
                    'id':4,
                    "menu":'Shift Schedule Wise Attandance Compare Summary Report',
                    "icon":<Torus className="text-card-foreground" size={15}/>,
                    "submenu":[],
                    "router-link":'/outlet/employeeShiftScheduleWiseAttandanceCompareSummaryReport',
                    "access_by":[],
                    
                }
            ],
        },
        {
            'id':11,
            "menu":'IDCard',
            "icon":<CreditCard  className="text-card-foreground" size={15}/>,
            "access_by":[1,8,9,12],
            "userType":["E"],
            "submenu":[],
            "router-link":'/outlet/idCard',
            "target":"_self"
        },
        {
            'id':12,
            "menu":'Track Employee',
            "icon":<MapPin  className="text-card-foreground" size={15}/>,
            "access_by":[1,8,9,12],
            "userType":["A"],
            "submenu":[],
            "router-link":'/outlet/track_emp',
            "target":"_self"
        },
        {
            'id':13,
            "menu":'Request Raise',
            "icon":<ReceiptJapaneseYen  className="text-card-foreground" size={15}/>,
            "access_by":[10],
            "userType":["E"],
            "submenu":[],
            "router-link":'/outlet/request',
            "target":"_self"
        },
        {
            'id':14,
            "menu":'All Request',
            "icon":<ReceiptJapaneseYen  className="text-card-foreground" size={15}/>,
            "access_by":[1,8,9,12],
            "userType":["A"],
            "submenu":[],
            "router-link":'/outlet/allRequest',
            "target":"_self"
        },
        {
            'id':5,
            "menu":'Logout',
            "icon":<LogOut className="text-card-foreground" size={15}/>,
            "submenu":[],
            "router-link":'/',
            "target":"_self",
            "access_by":[],
        }
    ]
    export const MeAttandanceMenus = [
        {
            'id':1,
            "menuName":'Attandance Log',
            "icon":<Logs className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'logs',
            "target":"_self",
            "access_by":[10],
            "userType":['E']
        },
        {
            'id':2,
            "menuName":'Calendar',
            "icon":<Calendar className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'shiftschedule',
            "target":"_self",
            "access_by":[10],
            "userType":['E']
        },
        {
            'id':3,
            "menuName":'Attandance Requests',
            "icon":<GitPullRequest className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'requests',
            "target":"_self",
            "access_by":[10],
            "userType":['E']
        },
    ]
    export const RequestMenus = [
         
        {
            'id':3,
            "menuName":'Leave',
            "icon":<LucideHome className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'leave_req',
            "access_by":[10],
            "userType":['E']
        },
        {
            'id':4,
            "menuName":'Leave',
            "icon":<LucideHome className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'leave',
            "access_by":[1,8,9,12],
            "userType":['A']
        },
        {
            'id':7,
            "menuName":'Visitory Notify',
            "icon":<LucideHome className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'visitor_notify_req',
            "access_by":[10],
            "userType":['E']
        },
        {
            'id':6,
            "menuName":'Visitory Notify',
            "icon":<LucideHome className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'visitor_notify',
            "access_by":[1,8,9,12],
            "userType":['A']
        },
        {
            'id':1,
            "menuName":'WFH/OSV',
            "icon":<LucideHome className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'raise',
            "access_by":[10],
            "userType":['E']
        },
        {
            'id':2,
            "menuName":'WFH/OSV',
            "icon":<LucideHome className="text-card-foreground" size={15}/>,
            "children":[],
            "route":'wfh',
            "access_by":[1,8,9,12],
            "userType":['A']
        },
    ]




